In [ ]:
import numpy as np
import matplotlib.pyplot as plt

## Alternate thought ##

In [ ]:
def M_chain():
    x = np.random.randint(0,10)
    y = np.random.randint(0,10)
    n = 20
    
    print(x,y)
    
    chain = np.zeros(n)
    chain[0] = x
    chain[1] = y
    
    for i in range(n-2):
        summ = chain[i] + chain[i+1]
        if summ > 9:
            value = 1
        else:
            value = summ
        chain[i+2] = value
    
    return chain

In [ ]:
for i in range(5):
    a = M_chain()
    print(a)

2 6
[2. 6. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1.]
8 9
[8. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1.]
0 9
[0. 9. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1.]
6 7
[6. 7. 1. 8. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1.]
9 6
[9. 6. 1. 7. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5.]


In [ ]:
def check_M_theory():
    index = np.zeros((10,10))
    N = 20
    count = 0
    for i in range(10):
        for j in range(10):
            if index[i,j] == 0:
                index[i,j] = 1
                chain = np.zeros(N)
                chain[0] = i
                chain[1] = j
                old = i
                new = j
                for n in range(N-2): 
                    summ = chain[n] + chain[n+1]
                    if summ > 9:
                        value = 1
                    else:
                        value = summ
                    old = new
                    new = value
                    
                    index[int(old),int(new)] = 1
                    
                    chain[n+2] = new
                print(index)
                print()
                print(chain)
                print()
                print('-'*100)
                print()
                count += 1
    truth = np.array_equal(index, np.ones((10,10)))
    return truth, count

In [ ]:
truth2, count2 = check_M_theory()
print(truth2)
print(count2)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

----------------------------------------------------------------------------------------------------

[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

[0. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2.]

----------------------------------------------------------------------------------------------------

[[1. 1



[7. 6. 1. 7. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5.]

----------------------------------------------------------------------------------------------------

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]

[8. 0. 8. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5. 8.]

----------------------------------------------------------------------------------------------------

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]

[8. 