In [1]:
import numpy as np
import matplotlib.pyplot as plt
import operator
from itertools import permutations as perm 

import random as rand 
from numba import jit

## Generate the 3x3 grid with spiral of integers ##

In [2]:
grid0 = np.array([[5,4,3], [6,1,2], [7,8,9]])
print(grid0)

[[5 4 3]
 [6 1 2]
 [7 8 9]]


In [3]:
ops = {"+": operator.add, "-": operator.sub, "*": operator.mul, "/": operator.truediv}
def operate(int1, op, int2):
    return ops[op](int1,int2)

In [4]:
def classify(array,up, right, down, left):
    if array[0] == 0:
        if array[1] == 1:
            return right
        elif array[1] == -1:
            return left
        else:
            print("Array not looking as expected")
            raise ValueError
    elif array[1] == 0:
        if array[0] == 1:
            return down
        elif array[0] == -1:
            return up
        else:
            print("Array not looking as expected")
            raise ValueError
    else:
        print("Array not looking as expected")
        raise ValueError

In [5]:
def arrows(grid, operations):
    up, right, down, left = operations
    n = (np.shape(grid)[0])**2
    #arrow = np.empty(8,dtype= str)
    arrow = []
    first1, first2 = np.where(grid == 1)
    first = np.concatenate((first1, first2))
    for i in range(2,n+1):
        second1,second2 = np.where(grid == i)
        second = np.concatenate((second1, second2))
        #arrow[i-2] = classify(second-first)
        direction = classify(second-first, up, right, down, left)
        arrow.append(direction)
        first = second
    return arrow

In [6]:
operation0 = ['+','-','*','/']
arrow0 = arrows(grid0, operation0)
print(arrow0)

['-', '+', '/', '/', '*', '*', '-', '-']


In [7]:
total = 1
for i in range(len(arrow0)):
    print(i+1, arrow0[i], i+2)
    print(operate(i+1, arrow0[i], i+2))
    
for j in range(len(arrow0)):
    total = operate(total, arrow0[j], j+2)
print(total)

1 - 2
-1
2 + 3
5
3 / 4
0.75
4 / 5
0.8
5 * 6
30
6 * 7
42
7 - 8
-1
8 - 9
-1
-12.799999999999999


In [8]:
def problem1(grid, operations):
    arrow_problem = arrows(grid, operations)
    total = 1
    for i in range(len(arrow_problem)):
        total = operate(total, arrow_problem[i], i+2)
    return total, operations

In [9]:
# Create the list operation permutations
l = list(perm(operation0))
for item in l:
    print(item)

('+', '-', '*', '/')
('+', '-', '/', '*')
('+', '*', '-', '/')
('+', '*', '/', '-')
('+', '/', '-', '*')
('+', '/', '*', '-')
('-', '+', '*', '/')
('-', '+', '/', '*')
('-', '*', '+', '/')
('-', '*', '/', '+')
('-', '/', '+', '*')
('-', '/', '*', '+')
('*', '+', '-', '/')
('*', '+', '/', '-')
('*', '-', '+', '/')
('*', '-', '/', '+')
('*', '/', '+', '-')
('*', '/', '-', '+')
('/', '+', '-', '*')
('/', '+', '*', '-')
('/', '-', '+', '*')
('/', '-', '*', '+')
('/', '*', '+', '-')
('/', '*', '-', '+')


In [10]:
# Check all of the spiral cases
for operation in l:
    total, item = problem1(grid0, operation)
    print(total)
    print(item)
    print()
    print('-'*100)
    print()

-12.799999999999999
('+', '-', '*', '/')

----------------------------------------------------------------------------------------------------

-16.047619047619047
('+', '-', '/', '*')

----------------------------------------------------------------------------------------------------

-918.0
('+', '*', '-', '/')

----------------------------------------------------------------------------------------------------

-6.857142857142857
('+', '*', '/', '-')

----------------------------------------------------------------------------------------------------

0.7916666666666666
('+', '/', '-', '*')

----------------------------------------------------------------------------------------------------

-3.2083333333333335
('+', '/', '*', '-')

----------------------------------------------------------------------------------------------------

17.0
('-', '+', '*', '/')

----------------------------------------------------------------------------------------------------

17.0
('-', '+', '/', '

In [11]:
total_array = np.zeros(len(l))
for k in range(len(l)):
    total, item = problem1(grid0, l[k])
    total_array[k] = total

argmax = np.argmax(total_array)
print(f"The maximum total occured for {l[argmax]} and was {total_array[argmax]}")

The maximum total occured for ('-', '*', '+', '/') and was 932.4


### Create the alternative 3x3 arrays ###

In [13]:
arrangement1 = np.array([[1,2,9],[4,3,8],[5,6,7]])
print(arrangement1)

total_array1 = np.zeros(len(l))
for k in range(len(l)):
    total, item = problem1(arrangement1, l[k])
    total_array1[k] = total

argmax1 = np.argmax(total_array1)
print(f"The maximum total occured for {l[argmax1]} and was {total_array1[argmax1]}")

#print(arrows(arrangement1, l[argmax1]))

[[1 2 9]
 [4 3 8]
 [5 6 7]]
The maximum total occured for ('*', '+', '/', '-') and was 892.8000000000001


In [14]:
arrangement2 = np.array([[1,2,3],[6,5,4],[7,8,9]])
print(arrangement2)

total_array2 = np.zeros(len(l))
for k in range(len(l)):
    total, item = problem1(arrangement2, l[k])
    total_array2[k] = total

argmax2 = np.argmax(total_array2)
print(f"The maximum total occured for {l[argmax2]} and was {total_array2[argmax2]}")


[[1 2 3]
 [6 5 4]
 [7 8 9]]
The maximum total occured for ('-', '*', '+', '/') and was 528.0


In [15]:
arrangement3 = np.array([[1,2,3],[8,9,4],[7,6,5]])
print(arrangement3)

total_array3 = np.zeros(len(l))
for k in range(len(l)):
    total, item = problem1(arrangement3, l[k])
    total_array3[k] = total

argmax3 = np.argmax(total_array3)
print(f"The maximum total occured for {l[argmax3]} and was {total_array3[argmax3]}")


[[1 2 3]
 [8 9 4]
 [7 6 5]]
The maximum total occured for ('*', '-', '/', '+') and was 93.4


In [16]:
arrangement4 = np.array([[1,2,3],[8,7,4],[9,6,5]])
total_array4 = np.zeros(len(l))
for k in range(len(l)):
    total, item = problem1(arrangement4, l[k])
    total_array4[k] = total

argmax4 = np.argmax(total_array4)
print(f"The maximum total occured for {l[argmax4]} and was {total_array4[argmax4]}")

The maximum total occured for ('-', '/', '+', '*') and was 393.00000000000006


## Extended problem ##

In [17]:
n = 3 
# coordinate of 1
range1 = int(np.ceil(n/2))
loc_1 = []
for i in range(range1):
    for j in range(range1):
        loc_1.append((i,j))
print(loc_1)
print(loc_1[1])


[(0, 0), (0, 1), (1, 0), (1, 1)]
(0, 1)


In [18]:
# make arrays
array_options = [loc_1]
for i in range(1,2):
    new_options = []
    print(array_options)
    for option in array_options[i-1]:
        new_option1 = np.array([1,0]) + np.asarray(option)
        new_option2 = np.array([0,1]) + np.asarray(option)
        print(new_option1)
        print(new_option2)
        new_options.append([new_option1, new_option2])
    array_options.append(new_options)
print(array_options)
print()
print(array_options[1][0])

[[(0, 0), (0, 1), (1, 0), (1, 1)]]
[1 0]
[0 1]
[1 1]
[0 2]
[2 0]
[1 1]
[2 1]
[1 2]
[[(0, 0), (0, 1), (1, 0), (1, 1)], [[array([1, 0]), array([0, 1])], [array([1, 1]), array([0, 2])], [array([2, 0]), array([1, 1])], [array([2, 1]), array([1, 2])]]]

[array([1, 0]), array([0, 1])]


In [21]:
def direction_generator(int):
    up = np.array([-1,0])
    right = np.array([0,1])
    down = np.array([1,0])
    left = np.array([0,-1])
    if int == 0:
        direction = up
    elif int == 1:
        direction = right
    elif int == 2:
        direction = down
    elif int == 3:
        direction = left
    else: 
        int = int(4*rand.random())
        direction = direction_generator(int)
    return direction

In [45]:
@jit 
def move_choices(array,previous_row, previous_column):
    n = np.shape(array)[0]
    moves = []
    up = (previous_row - 1, previous_column + 0)
    right = (previous_row + 0, previous_column + 1)
    down = (previous_row + 1, previous_column + 0)
    left = (previous_row + 0, previous_column - 1)
    possibilities = [up,right,down,left]
    #print(possibilities)
    for direc in possibilities:
        #print(direc)
        direc_row, direc_column = direc
        if not((direc_row < 0) or (direc_column < 0) or (direc_row > n-1) or (direc_column > n-1)):
            if array[direc_row, direc_column] == 0:
                #print("YES")
                moves.append(direc)
    return moves

In [46]:
@jit 
def array_structure(n,row1, column1, counter=0):
    array = np.zeros((n,n))
    move1_a = row1
    move1_b = column1
    array[move1_a, move1_b] = 1
    #print(array)
    last_loc_a, last_loc_b = move1_a, move1_b
    for i in range(2,n*n+1):
        moves = move_choices(array, last_loc_a, last_loc_b)
        l = len(moves)
        #print(f"length of moves is {l}")
        if counter > 100:
            array = str("No array")
            break
        elif l == 0:
            counter += 1
            array = array_structure(n,row1, column1, counter = counter)
            break
        else:
            index = int(l * rand.random())
            while index == l:
                index = int(l * rand.random())
            move_a, move_b = moves[index]
            array[move_a, move_b] = i 
            last_loc_a, last_loc_b = move_a, move_b
            #print(array)
    counter = 0
    return array

In [35]:
print(array_structure(3,1,1))

[[5. 6. 7.]
 [4. 1. 8.]
 [3. 2. 9.]]


In [36]:
print(array_structure(3,0,0))

[[1. 4. 5.]
 [2. 3. 6.]
 [9. 8. 7.]]


In [47]:
@jit 
def max_arrangement(array,permutations):
    total_array = np.zeros(len(permutations))
    for k in range(len(permutations)):
        total, item = problem1(array, permutations[k])
        total_array[k] = total
    return np.max(total_array)

In [49]:
# Checking my function performs correctly in a known case
arrangement3 = np.array([[1,2,3],[8,9,4],[7,6,5]])
print(max_arrangement(arrangement3,l))

93.4


In [71]:
@jit 
def extension(repeats, n):
    range1 = int(np.ceil(n/2))
    locations = []
    for i in range(range1):
        for j in range(range1):
            locations.append((i,j))

    l = list(perm(operation0))
    iterations = int(repeats)
    
    max = 0
    max_array = np.zeros((n,n))
    total_sum = []
    for pair in locations:
        index1_a, index1_b = pair
        #print(index1_a)
        #print(index1_b)
        for j in range(iterations):
            array = array_structure(n,index1_a, index1_b)
            if not(type(array) == str):
                total_array = np.zeros(len(l))
                for k in range(len(l)):
                    total, item = problem1(array, l[k])
                    total_array[k] = total
                max_in_arrangement = np.max(total_array)
                total_sum.append(max_in_arrangement)
                if max_in_arrangement > max:
                    max = max_in_arrangement
                    max_array = array
                    
    maxima = set(total_sum)
    return maxima, max, max_array

In [78]:
maxima3, max3, max_array3 = extension(1e3,3)
print(maxima3)
print()
print(max3)
print(max_array3)
print()

{932.4, 393.00000000000006, 528.0, 892.8000000000001, 93.4}

932.4
[[5. 6. 7.]
 [4. 1. 8.]
 [3. 2. 9.]]



In [79]:
maxima4, max4, max_array4 = extension(1e3, 4)
print(maxima4)
print()
print(max4)
print(max_array4)
print()

{161280.0, 389760.0, 1975680.0000000005, 119171.73333333334, 2565.318181818182, 6279.5, 46343.5, 5257.25, 38794.133928571435, 30602.000000000004, 54155.142857142855, 62349.5, 29325.600000000002, 6797.25, 115728.0, 4497.6, 5005.642857142857, 121226.0, 4503.5, 62107.5, 53020.45454545456, 4895.5, 146720.0, 27426.357142857145, 29091.42857142857, 40740.4, 89770.66666666666, 8747.25, 22572.190476190473, 33454.42045454545, 60720.812500000015, 14897.25, 5554.285714285714, 97719.99999999999, 32058.39772727272, 1215.95, 1088.7333333333333, 75840.0, 5312.666666666667, 1068480.0, 4292.625, 216900.00000000003, 120390.66666666667, 90176.91666666666, 115400.0, 118208.99999999999, 85962.14814814816, 8654.933333333336, 85839.97222222222, 357840.00000000006, 4087.15625, 7637.333333333333, 3801.6, 19162.285714285714, 45530.66666666667, 37468.0, 120922.66666666666, 16607.692307692305, 5681760.0, 115296.00000000001, 1379.956043956044, 19174.09090909091, 20711.625, 54007.03571428571, 55789.42857142857, 6391

In [80]:
maxima5, max5, max_array5 = extension(1e3, 5)
#print(maxima5)
#print()
print(max5)
print(max_array5)
print()

1362604465200.0
[[ 1.  2.  3.  4.  5.]
 [10.  9.  8.  7.  6.]
 [11. 12. 13. 14. 15.]
 [20. 19. 18. 17. 16.]
 [21. 22. 23. 24. 25.]]



In [81]:
maxima6, max6, max_array6 = extension(2e3, 6)
#print(maxima5)
#print()
print(max6)
print(max_array6)
print()

1.9380822968662848e+17
[[36. 25. 24. 23. 16. 15.]
 [35. 26.  1. 22. 17. 14.]
 [34. 27.  2. 21. 18. 13.]
 [33. 28.  3. 20. 19. 12.]
 [32. 29.  4.  7.  8. 11.]
 [31. 30.  5.  6.  9. 10.]]



In [83]:
print("Results for cases n=3,4,5,6 are shown below")
print()
print(f"The maximum value I can make for n=3 is {max3}, which is generated by the following array: \n {max_array3}")
print(f"The maximum value I can make for n=4 is {max4}, which is generated by the following array: \n {max_array4}")
print(f"The maximum value I can make for n=5 is {max5}, which is generated by the following array: \n {max_array5}")
print(f"The maximum value I can make for n=6 is {max6}, which is generated by the following array: \n {max_array6}")


Results for cases n=3,4,5,6 are shown below

The maximum value I can make for n=3 is 932.4, which is generated by the following array: 
 [[5. 6. 7.]
 [4. 1. 8.]
 [3. 2. 9.]]
The maximum value I can make for n=4 is 5681760.0, which is generated by the following array: 
 [[ 1.  8.  9. 16.]
 [ 2.  7. 10. 15.]
 [ 3.  6. 11. 14.]
 [ 4.  5. 12. 13.]]
The maximum value I can make for n=5 is 1362604465200.0, which is generated by the following array: 
 [[ 1.  2.  3.  4.  5.]
 [10.  9.  8.  7.  6.]
 [11. 12. 13. 14. 15.]
 [20. 19. 18. 17. 16.]
 [21. 22. 23. 24. 25.]]
The maximum value I can make for n=6 is 1.9380822968662848e+17, which is generated by the following array: 
 [[36. 25. 24. 23. 16. 15.]
 [35. 26.  1. 22. 17. 14.]
 [34. 27.  2. 21. 18. 13.]
 [33. 28.  3. 20. 19. 12.]
 [32. 29.  4.  7.  8. 11.]
 [31. 30.  5.  6.  9. 10.]]
