In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def chain(x = 0, y = 0, rand = True, n=22):
    if rand:
        x = np.random.randint(0,10)
        y = np.random.randint(0,10)
    
    print(x,y)
    
    chain = np.zeros(n)
    chain[0] = x
    chain[1] = y
    
    for i in range(n-2):
        chain[i+2] = ((chain[i] + chain[i+1]) % 10)
    
    return chain

In [3]:
for j in range(5):
    c = chain()
    print(c)


1 6
[1. 6. 7. 3. 0. 3. 3. 6. 9. 5. 4. 9. 3. 2. 5. 7. 2. 9. 1. 0. 1. 1.]
1 3
[1. 3. 4. 7. 1. 8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1. 8. 9. 7. 6. 3.]
9 4
[9. 4. 3. 7. 0. 7. 7. 4. 1. 5. 6. 1. 7. 8. 5. 3. 8. 1. 9. 0. 9. 9.]
6 9
[6. 9. 5. 4. 9. 3. 2. 5. 7. 2. 9. 1. 0. 1. 1. 2. 3. 5. 8. 3. 1. 4.]
9 0
[9. 0. 9. 9. 8. 7. 5. 2. 7. 9. 6. 5. 1. 6. 7. 3. 0. 3. 3. 6. 9. 5.]


Redefine chain function to have optional arguments 

In [4]:
for j in range(5):
    d = chain()
    print(d)

6 0
[6. 0. 6. 6. 2. 8. 0. 8. 8. 6. 4. 0. 4. 4. 8. 2. 0. 2. 2. 4. 6. 0.]
4 6
[4. 6. 0. 6. 6. 2. 8. 0. 8. 8. 6. 4. 0. 4. 4. 8. 2. 0. 2. 2. 4. 6.]
9 2
[9. 2. 1. 3. 4. 7. 1. 8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1. 8. 9. 7.]
8 7
[8. 7. 5. 2. 7. 9. 6. 5. 1. 6. 7. 3. 0. 3. 3. 6. 9. 5. 4. 9. 3. 2.]
5 6
[5. 6. 1. 7. 8. 5. 3. 8. 1. 9. 0. 9. 9. 8. 7. 5. 2. 7. 9. 6. 5. 1.]


Actually create new function that does a similar job but looks for a certain duple whilst the chain is made

In [12]:
#for j in range(20):
#    d = chain(n=40)
#    print(d)

In [6]:
def check_theory():
    index = np.zeros((10,10))
    N = 100
    count = 0
    for i in range(10):
        for j in range(10):
            if index[i,j] == 0:
                index[i,j] = 1
                chain = np.zeros(N)
                chain[0] = i
                chain[1] = j
                old = i
                new = j
                for n in range(N-2):     
                    old = new
                    new = (chain[n] + chain[n+1]) % 10
                    
                    index[int(old),int(new)] = 1
                    
                    chain[n+2] = new
                print(index)
                print()
                print(chain)
                print()
                print('-'*100)
                print()
                count += 1
    truth = np.array_equal(index, np.ones((10,10)))
    return truth, count

In [7]:
truth, count = check_theory()
print(truth)
print(count)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]

----------------------------------------------------------------------------------------------------

[[1. 1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 0. 1. 1.

## Miranda thoughts ##

In [8]:
def M_chain():
    x = np.random.randint(0,10)
    y = np.random.randint(0,10)
    n = 20
    
    print(x,y)
    
    chain = np.zeros(n)
    chain[0] = x
    chain[1] = y
    
    for i in range(n-2):
        summ = chain[i] + chain[i+1]
        if summ > 9:
            value = 1
        else:
            value = summ
        chain[i+2] = value
    
    return chain

In [9]:
for i in range(5):
    a = M_chain()
    print(a)

7 8
[7. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9.]
7 0
[7. 0. 7. 7. 1. 8. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5.]
0 7
[0. 7. 7. 1. 8. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5. 8.]
1 5
[1. 5. 6. 1. 7. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3.]
7 5
[7. 5. 1. 6. 7. 1. 8. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3.]


In [10]:
def check_M_theory():
    index = np.zeros((10,10))
    N = 20
    count = 0
    for i in range(10):
        for j in range(10):
            if index[i,j] == 0:
                index[i,j] = 1
                chain = np.zeros(N)
                chain[0] = i
                chain[1] = j
                old = i
                new = j
                for n in range(N-2): 
                    summ = chain[n] + chain[n+1]
                    if summ > 9:
                        value = 1
                    else:
                        value = summ
                    old = new
                    new = value
                    
                    index[int(old),int(new)] = 1
                    
                    chain[n+2] = new
                print(index)
                print()
                print(chain)
                print()
                print('-'*100)
                print()
                count += 1
    truth = np.array_equal(index, np.ones((10,10)))
    return truth, count

In [11]:
truth2, count2 = check_M_theory()
print(truth2)
print(count2)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

----------------------------------------------------------------------------------------------------

[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

[0. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2. 3. 5. 8. 1. 9. 1. 1. 2.]

----------------------------------------------------------------------------------------------------

[[1. 1