In [51]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib osx

In [6]:
def chain(x = 0, y = 0, rand = True, n=22):
    if rand:
        x = np.random.randint(0,10)
        y = np.random.randint(0,10)
    
    print(f"({x},{y})")
    
    chain = np.zeros(n)
    chain[0] = x
    chain[1] = y
    
    for i in range(n-2):
        chain[i+2] = ((chain[i] + chain[i+1]) % 10)
    
    return chain

First I look at extending the sequence already given using my chain idea.

In [7]:
example = chain(1,5,rand=False, n=30)
print(example)

(1,5)
[1. 5. 6. 1. 7. 8. 5. 3. 8. 1. 9. 0. 9. 9. 8. 7. 5. 2. 7. 9. 6. 5. 1. 6.
 7. 3. 0. 3. 3. 6.]


I specialise the problem below for some random starting pairs of integers.

In [24]:
for j in range(5):
    c = chain()
    print(c)

(1,0)
[1. 0. 1. 1. 2. 3. 5. 8. 3. 1. 4. 5. 9. 4. 3. 7. 0. 7. 7. 4. 1. 5.]
(6,5)
[6. 5. 1. 6. 7. 3. 0. 3. 3. 6. 9. 5. 4. 9. 3. 2. 5. 7. 2. 9. 1. 0.]
(1,2)
[1. 2. 3. 5. 8. 3. 1. 4. 5. 9. 4. 3. 7. 0. 7. 7. 4. 1. 5. 6. 1. 7.]
(6,7)
[6. 7. 3. 0. 3. 3. 6. 9. 5. 4. 9. 3. 2. 5. 7. 2. 9. 1. 0. 1. 1. 2.]
(0,3)
[0. 3. 3. 6. 9. 5. 4. 9. 3. 2. 5. 7. 2. 9. 1. 0. 1. 1. 2. 3. 5. 8.]


I hypothesised there was only one sequence, but we check this claim below. If there is only one, there should be 100 pairs of integers (since we have 10 options per integer).

Whilst writing the code, clearly there is another sequence of just zeros so i now look for 99 pairs in my sequence not starting 0,0.

In [25]:
x1 = 0
x2 = 1
x3 = (x1 + x2) % 10
count = 1

a = x2
b = x3
for i in range(100):
    if a == x1 and b == x2:
        print(count)
        break
    else:
        count += 1
        intermediate = (a + b) % 10
        a = b
        b = intermediate

60


This was not the result that I was expecting, therefore my initial hypothesis must have been false. Evidently there are some pairs which don't get made when starting with 01. Therefore, I now write a code to check off the pairs that have been generated and to generate new sequences with those ungenerated pairs. In my notes, I found 6 sequences, so I am expecting a count of 6 different sequences (including the 00 sequence).

In [26]:
def check_theory():
    index = np.zeros((10,10))
    N = 100
    count = 0
    for i in range(10):
        for j in range(10):
            if index[i,j] == 0:
                index[i,j] = 1
                chain = np.zeros(N)
                chain[0] = i
                chain[1] = j
                old = i
                new = j
                for n in range(N-2):     
                    old = new
                    new = (chain[n] + chain[n+1]) % 10
                    
                    index[int(old),int(new)] = 1
                    
                    chain[n+2] = new
                print(index)
                print()
                print(chain)
                print()
                print('-'*100)
                print()
                count += 1
    truth = np.array_equal(index, np.ones((10,10)))
    return truth, count

In [28]:
truth, count = check_theory()
if truth:
    print("All pairs have been generated from the number of sequneces below")
    print(f"The number of bracelets generated was {count}")
else:
    print("There is a mistake in the function since not all pairs have been generated")

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]

----------------------------------------------------------------------------------------------------

[[1. 1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 0. 1.]
 [0. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 0. 1. 1.

## Extending the Problem ##
We could generalise this problem by asking how many bracelets are there for any given integer n, where we pick 2 numberd less than n to start with.

In [37]:
def extension(n):
    index = np.zeros((n,n))
    N = n**2
    count = 0
    for i in range(n):
        for j in range(n):
            if index[i,j] == 0:
                index[i,j] = 1
                chain = [i,j]
                old = i
                new = j
                for k in range(N-2):     
                    old = new
                    new = (chain[k] + chain[k+1]) % n
                    if index[int(old),int(new)] == 1:
                        break
                    else:
                        index[int(old),int(new)] = 1
                        chain.append(new)
                count += 1
    truth = np.array_equal(index, np.ones((n,n)))
    assert truth == True
    return count

In [60]:
#Check code works for n = 10
assert extension(10) == 6
n0 = 5
n1 = 50
bracelets = np.zeros(n1-n0 + 1)
for n in range(n0,n1+1):
    bracelets[n-n0] = extension(n)
plt.plot((n0 + np.arange(n1-n0+1)),bracelets, label = 'number of bracelets')
#plt.plot((n0 + np.arange(n1-n0+1)), (n0 + np.arange(n1-n0+1)), 'r--', label = 'y=x')
plt.xlabel("n")
plt.ylabel("number of bracelets")
plt.title("Extension of bracelet problem - effect of choice of n")
#plt.legend()
plt.show()

plt.savefig('bracelet_extension.pdf')