In [35]:
import numpy as np 
import matplotlib.pyplot as plt 
from numpy.linalg import det
%matplotlib osx

For an nxn matrix, there are $2^{n^2}$ choices of game outcomes. Hence we will look at some of the cases for small n to start with

Assume the grid is labelled for the players such that the coordinates (1,1), (n,n) represent the top left and bottom right grid spaces respecitvely

In [54]:
def check(x,y,matrix):
    dim = np.shape(matrix)[0]
    while True:
        if not(1<= x <= dim):
            print('NO! Please choose an integer between 1 and n. Choose again')
            x = int(input('It is still your turn: Which row would you like to choose from?'))
            y = int(input(f'It is still your turn: Which column would you like to choose from in row {x}?'))
        elif not(1<= y <= dim):
            print('NO! Please choose an integer between 1 and n. Choose again')
            x = int(input('It is still your turn: Which row would you like to choose from?'))
            y = int(input(f'It is still your turn: Which column would you like to choose from in row {x}?'))
        elif not (matrix[x-1,y-1] == '-'):
            print('NO! Please choose an empty element to place your piece. Choose again')
            x = int(input('It is still your turn: Which row would you like to choose from?'))
            y = int(input(f'It is still your turn: Which column would you like to choose from in row {x}?'))
        else:
            return x,y

In [55]:
def matrix_game(n,go = 1):
    matrix = np.full((n,n), '-')
    if go != 1 and go != 0:
        raise ValueError('The varibale go must be either 0 or 1')
    print(matrix)
    while np.any(matrix == '-'):
        if go == 1:
            x = int(input('Your turn: Which row would you like to choose from?'))
            y = int(input(f'Your turn: Which column would you like to choose from in row {x}?'))
            x,y = check(x,y,matrix)
            matrix[x-1,y-1] = int(0)
            go = 0
            print(matrix)
        else:
            index = np.where(matrix == '-')
            #print(index)
            l = len(index[0])
            #print(l)
            z = rng.integers(0, l)
            a = index[0][z]
            b = index[1][z]
            matrix[a,b] = int(1)
            go = 1
            print(matrix)
    output = matrix.astype(int)
    d = det(output)
    #print(det)
    if d == 0:
        print(f'YOU WIN - determinant was {d}')
    else:
        print(f'YOU LOSE - determinant was {d}')
    return _

In [37]:
rng = np.random.default_rng()
m = matrix_game(2)


[['-' '-']
 ['-' '-']]
[['0' '-']
 ['-' '-']]
(array([0, 1, 1]), array([1, 0, 1]))
3
[['0' '1']
 ['-' '-']]
NO! Please choose an empty element to place your piece. Choose again
[['0' '1']
 ['0' '-']]
(array([1]), array([1]))
1
[['0' '1']
 ['0' '1']]
YOU WIN - determinant was 0.0


In [38]:
rng = np.random.default_rng()
matrix_game(3)

[['-' '-' '-']
 ['-' '-' '-']
 ['-' '-' '-']]
[['-' '-' '-']
 ['-' '0' '-']
 ['-' '-' '-']]
(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 2, 0, 1, 2]))
8
[['-' '-' '-']
 ['-' '0' '-']
 ['1' '-' '-']]
[['-' '-' '-']
 ['-' '0' '0']
 ['1' '-' '-']]
(array([0, 0, 0, 1, 2, 2]), array([0, 1, 2, 0, 1, 2]))
6
[['-' '-' '1']
 ['-' '0' '0']
 ['1' '-' '-']]
[['-' '-' '1']
 ['0' '0' '0']
 ['1' '-' '-']]
(array([0, 0, 2, 2]), array([0, 1, 1, 2]))
4
[['-' '1' '1']
 ['0' '0' '0']
 ['1' '-' '-']]
[['0' '1' '1']
 ['0' '0' '0']
 ['1' '-' '-']]
(array([2, 2]), array([1, 2]))
2
[['0' '1' '1']
 ['0' '0' '0']
 ['1' '-' '1']]
[['0' '1' '1']
 ['0' '0' '0']
 ['1' '0' '1']]
YOU WIN - determinant was 0.0


''

In [40]:
rng = np.random.default_rng()
matrix_game(4)

[['-' '-' '-' '-']
 ['-' '-' '-' '-']
 ['-' '-' '-' '-']
 ['-' '-' '-' '-']]
[['-' '-' '-' '-']
 ['-' '-' '-' '-']
 ['-' '-' '0' '-']
 ['-' '-' '-' '-']]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 3, 0, 1, 2, 3]))
15
[['-' '-' '1' '-']
 ['-' '-' '-' '-']
 ['-' '-' '0' '-']
 ['-' '-' '-' '-']]
NO! Please choose an empty element to place your piece. Choose again
[['-' '-' '1' '-']
 ['-' '-' '-' '-']
 ['-' '0' '0' '-']
 ['-' '-' '-' '-']]
(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3]), array([0, 1, 3, 0, 1, 2, 3, 0, 3, 0, 1, 2, 3]))
13
[['-' '-' '1' '-']
 ['-' '-' '-' '-']
 ['-' '0' '0' '1']
 ['-' '-' '-' '-']]
[['-' '-' '1' '-']
 ['-' '0' '-' '-']
 ['-' '0' '0' '1']
 ['-' '-' '-' '-']]
(array([0, 0, 0, 1, 1, 1, 2, 3, 3, 3, 3]), array([0, 1, 3, 0, 2, 3, 0, 0, 1, 2, 3]))
11
[['-' '-' '1' '-']
 ['-' '0' '-' '-']
 ['-' '0' '0' '1']
 ['-' '1' '-' '-']]
[['-' '-' '1' '-']
 ['-' '0' '-' '-']
 ['-' '0' '0' '1']
 ['0' '1' '-' '-']]
(array([0, 0, 0

''

I try to write a strategy for the other player. That is to make a diagonal of 1s. If the computer does this, will it always win?

I assume the game is for n>2 since i know i can always win if n=2.

In [90]:
def strategy1(move_matrix,last_move, my_move):
    n = np.shape(move_matrix)[0]
    x,y = my_move
    a,b = last_move
    move_matrix[x,y] = 0
    #for i in range(n-1):
        #move_matrix[(x+i)%n, (y+i)%n] = 2
        #move_matrix[(x+i)%n, (y-i)%n] = 2
    if not (last_move == (-1,-1)):
        move_matrix[a,b] = 20
        target1 = True
        target2 = True
        for j in range(n):
            for k in range(n):
                if not ((k == (b-a+j)%n) or (k == (b+a-j)%n)):
                    if not (move_matrix[j,k] == 0):
                        move_matrix[j,k] = 2
                if ((k == (y-x+j)%n) or (k == (y+x-j)%n)):
                    if not (move_matrix[j,k] == 0):
                        move_matrix[j,k] = 2
                #else:
                    #if not (move_matrix[j,k] == 0)
    print('*'*100)
    print(move_matrix)
    print('*'*100)
    available_move = np.any(move_matrix == 1)
    if available_move:
        return move_matrix, available_move
    else:
        #Reconstruct move matrix to find a new strategy
        new_moves, available_move = change_strat(move_matrix,n)
        print('*'*100)
        print(new_moves)
        print('*'*100)
        return new_moves, available_move
        

In [91]:
def change_strat(move_matrix,n):
    new_moves = np.copy(move_matrix)
    for j in range(n):
        if not (move_matrix[0,j] == 0):
            pos = True
            neg = True
            for k in range(n-1):
                if (move_matrix[k+1, ((j+k+1) %n)] == 0):
                    pos = False
                if (move_matrix[k+1, ((j-k-1) %n)] == 0):
                    neg = False
                if (pos == False) and (neg == False):
                    break
            if (pos == True):
                for q in range(n):
                    if not (new_moves[q,(j+q)%n] == 20):
                        new_moves[q,(j+q)%n] = 1
            if (neg == True):
                for q in range(n):
                    if not (new_moves[q,(j-q)%n] == 20):
                        new_moves[q,(j-q)%n] = 1
    indices = np.where(new_moves == 2)
    l = len(indices[0])
    for r in range(l):
        ind_i = indices[0][r]
        ind_j = indices[1][r]
        new_moves[ind_i, ind_j] = 0
    if np.any(new_moves == 1):
        return new_moves, True
    else:
        return new_moves, False

In [92]:
x = np.array([[2,0,2,20],
          [0,2,2,2],
          [0,20,2,2],
          [0,20,2,2]])
y, truth = change_strat(x,4)
print(y)
print(truth)

[[ 1  0  0 20]
 [ 0  1  0  1]
 [ 0 20  1  0]
 [ 0 20  0  1]]
True


In [93]:
def matrix_game_strat1(n,go = 1):
    matrix = np.full((n,n), '-')
    if go != 1 and go != 0:
        raise ValueError('The varibale go must be either 0 or 1')
    print(matrix)
    print()
    print('-'*100)
    print()
    last_move = (-1,-1)
    move_matrix = np.ones_like(matrix, dtype=int)
    while np.any(matrix == '-'):
        if go == 1:
            x = int(input('Your turn: Which row would you like to choose from?'))
            y = int(input(f'Your turn: Which column would you like to choose from in row {x}?'))
            x,y = check(x,y,matrix)
            matrix[x-1,y-1] = int(0)
            my_move = (x-1,y-1)
            go = 0
            print(matrix)
            print()
            print('-'*100)
            print()
        else:
            move_matrix, available_move = strategy1(move_matrix, last_move, my_move)
            if available_move: 
                index = np.where(move_matrix == 1)
                #print(index)
                l = len(index[0])
                #print(l)
                z = rng.integers(0, l)
                a = index[0][z]
                b = index[1][z]
                matrix[a,b] = int(1)
                last_move = (a,b)
                go = 1
                print(matrix)
                print()
                print('-'*100)
                print()
            else:
                #print('*'*100)
                #print(move_matrix)
                #print('*'*100)   
                index = np.where(matrix == '-')
                #print(index)
                l = len(index[0])
                #print(l)
                z = rng.integers(0, l)
                a = index[0][z]
                b = index[1][z]
                matrix[a,b] = int(1)
                last_move = (a,b)
                go = 1
                print(matrix)
                print()
                print('-'*100)
                print()
    output = matrix.astype(int)
    d = det(output)
    #print(det)
    if d == 0:
        print(f'YOU WIN - determinant was {d}')
    else:
        print(f'YOU LOSE - determinant was {d}')
    return _

In [94]:
rng = np.random.default_rng()
matrix_game_strat1(4)

[['-' '-' '-' '-']
 ['-' '-' '-' '-']
 ['-' '-' '-' '-']
 ['-' '-' '-' '-']]

----------------------------------------------------------------------------------------------------

[['0' '-' '-' '-']
 ['-' '-' '-' '-']
 ['-' '-' '-' '-']
 ['-' '-' '-' '-']]

----------------------------------------------------------------------------------------------------

****************************************************************************************************
[[0 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
****************************************************************************************************
[['0' '-' '-' '-']
 ['-' '-' '-' '-']
 ['-' '1' '-' '-']
 ['-' '-' '-' '-']]

----------------------------------------------------------------------------------------------------

[['0' '-' '-' '-']
 ['-' '-' '-' '-']
 ['0' '1' '-' '-']
 ['-' '-' '-' '-']]

----------------------------------------------------------------------------------------------------

*********************************

''